name: run0 build and unit tests
on: [push, pull_request, create]

jobs:
  basic_ci:
    if: github.event_name == 'pull_request'
    name: Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Build and install with default features
        run: cargo build

      - name: Run cargo test
        uses: marcopolo/cargo@master
        with:
          command: test

      - name: Run cargo fmt check
        uses: marcopolo/cargo@master
        with:
          command: fmt
          args: --all -- --check

      - name: Run rust lint check
        uses: marcopolo/cargo@master
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings